server:
  port: 9092
  servlet:
    context-path: /
    session:
      timeout: 300
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true

spring:
  application:
    name: app-order

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      key01: value01
      key02: value02